<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run()
    : void
    {
        DB::table('cities')->insert([
            ['name' => 'Chachapoyas', 'department_id' => 1],
            ['name' => 'Bagua', 'department_id' => 1],
            ['name' => 'Bongará', 'department_id' => 1],
            ['name' => 'Condorcanqui', 'department_id' => 1],
            ['name' => 'Luya', 'department_id' => 1],
            ['name' => 'Rodríguez de Mendoza', 'department_id' => 1],
            ['name' => 'Utcubamba', 'department_id' => 1],
            ['name' => 'Huaraz', 'department_id' => 2],
            ['name' => 'Aija', 'department_id' => 2],
            ['name' => 'Antonio Raymondi', 'department_id' => 2],
            ['name' => 'Asunción', 'department_id' => 2],
            ['name' => 'Bolognesi', 'department_id' => 2],
            ['name' => 'Carhuaz', 'department_id' => 2],
            ['name' => 'Carlos Fermín Fitzcarrald', 'department_id' => 2],
            ['name' => 'Casma', 'department_id' => 2],
            ['name' => 'Corongo', 'department_id' => 2],
            ['name' => 'Huari', 'department_id' => 2],
            ['name' => 'Huarmey', 'department_id' => 2],
            ['name' => 'Huaylas', 'department_id' => 2],
            ['name' => 'Mariscal Luzuriaga', 'department_id' => 2],
            ['name' => 'Ocros', 'department_id' => 2],
            ['name' => 'Pallasca', 'department_id' => 2],
            ['name' => 'Pomabamba', 'department_id' => 2],
            ['name' => 'Recuay', 'department_id' => 2],
            ['name' => 'Santa', 'department_id' => 2],
            ['name' => 'Sihuas', 'department_id' => 2],
            ['name' => 'Yungay', 'department_id' => 2],
            ['name' => 'Abancay', 'department_id' => 3],
            ['name' => 'Andahuaylas', 'department_id' => 3],
            ['name' => 'Antabamba', 'department_id' => 3],
            ['name' => 'Aymaraes', 'department_id' => 3],
            ['name' => 'Cotabambas', 'department_id' => 3],
            ['name' => 'Chincheros', 'department_id' => 3],
            ['name' => 'Grau', 'department_id' => 3],
            ['name' => 'Arequipa', 'department_id' => 4],
            ['name' => 'Camaná', 'department_id' => 4],
            ['name' => 'Caravelí', 'department_id' => 4],
            ['name' => 'Castilla', 'department_id' => 4],
            ['name' => 'Caylloma', 'department_id' => 4],
            ['name' => 'Condesuyos', 'department_id' => 4],
            ['name' => 'Islay', 'department_id' => 4],
            ['name' => 'La Uniòn', 'department_id' => 4],
            ['name' => 'Huamanga', 'department_id' => 5],
            ['name' => 'Cangallo', 'department_id' => 5],
            ['name' => 'Huanca Sancos', 'department_id' => 5],
            ['name' => 'Huanta', 'department_id' => 5],
            ['name' => 'La Mar', 'department_id' => 5],
            ['name' => 'Lucanas', 'department_id' => 5],
            ['name' => 'Parinacochas', 'department_id' => 5],
            ['name' => 'Pàucar del Sara Sara', 'department_id' => 5],
            ['name' => 'Sucre', 'department_id' => 5],
            ['name' => 'Víctor Fajardo', 'department_id' => 5],
            ['name' => 'Vilcas Huamán', 'department_id' => 5],
            ['name' => 'Cajamarca', 'department_id' => 6],
            ['name' => 'Cajabamba', 'department_id' => 6],
            ['name' => 'Celendín', 'department_id' => 6],
            ['name' => 'Chota', 'department_id' => 6],
            ['name' => 'Contumazá', 'department_id' => 6],
            ['name' => 'Cutervo', 'department_id' => 6],
            ['name' => 'Hualgayoc', 'department_id' => 6],
            ['name' => 'Jaén', 'department_id' => 6],
            ['name' => 'San Ignacio', 'department_id' => 6],
            ['name' => 'San Marcos', 'department_id' => 6],
            ['name' => 'San Miguel', 'department_id' => 6],
            ['name' => 'San Pablo', 'department_id' => 6],
            ['name' => 'Santa Cruz', 'department_id' => 6],
            ['name' => 'Prov. Const. del Callao', 'department_id' => 7],
            ['name' => 'Cusco', 'department_id' => 8],
            ['name' => 'Acomayo', 'department_id' => 8],
            ['name' => 'Anta', 'department_id' => 8],
            ['name' => 'Calca', 'department_id' => 8],
            ['name' => 'Canas', 'department_id' => 8],
            ['name' => 'Canchis', 'department_id' => 8],
            ['name' => 'Chumbivilcas', 'department_id' => 8],
            ['name' => 'Espinar', 'department_id' => 8],
            ['name' => 'La Convención', 'department_id' => 8],
            ['name' => 'Paruro', 'department_id' => 8],
            ['name' => 'Paucartambo', 'department_id' => 8],
            ['name' => 'Quispicanchi', 'department_id' => 8],
            ['name' => 'Urubamba', 'department_id' => 8],
            ['name' => 'Huancavelica', 'department_id' => 9],
            ['name' => 'Acobamba', 'department_id' => 9],
            ['name' => 'Angaraes', 'department_id' => 9],
            ['name' => 'Castrovirreyna', 'department_id' => 9],
            ['name' => 'Churcampa', 'department_id' => 9],
            ['name' => 'Huaytará', 'department_id' => 9],
            ['name' => 'Tayacaja', 'department_id' => 9],
            ['name' => 'Huánuco', 'department_id' => 10],
            ['name' => 'Ambo', 'department_id' => 10],
            ['name' => 'Dos de Mayo', 'department_id' => 10],
            ['name' => 'Huacaybamba', 'department_id' => 10],
            ['name' => 'Huamalíes', 'department_id' => 10],
            ['name' => 'Leoncio Prado', 'department_id' => 10],
            ['name' => 'Marañón', 'department_id' => 10],
            ['name' => 'Pachitea', 'department_id' => 10],
            ['name' => 'Puerto Inca', 'department_id' => 10],
            ['name' => 'Lauricocha ', 'department_id' => 10],
            ['name' => 'Yarowilca ', 'department_id' => 10],
            ['name' => 'Ica ', 'department_id' => 11],
            ['name' => 'Chincha ', 'department_id' => 11],
            ['name' => 'Nasca ', 'department_id' => 11],
            ['name' => 'Palpa ', 'department_id' => 11],
            ['name' => 'Pisco ', 'department_id' => 11],
            ['name' => 'Huancayo ', 'department_id' => 12],
            ['name' => 'Concepción ', 'department_id' => 12],
            ['name' => 'Chanchamayo ', 'department_id' => 12],
            ['name' => 'Jauja ', 'department_id' => 12],
            ['name' => 'Junín ', 'department_id' => 12],
            ['name' => 'Satipo ', 'department_id' => 12],
            ['name' => 'Tarma ', 'department_id' => 12],
            ['name' => 'Yauli ', 'department_id' => 12],
            ['name' => 'Chupaca ', 'department_id' => 12],
            ['name' => 'Trujillo ', 'department_id' => 13],
            ['name' => 'Ascope ', 'department_id' => 13],
            ['name' => 'Bolívar ', 'department_id' => 13],
            ['name' => 'Chepén ', 'department_id' => 13],
            ['name' => 'Julcán ', 'department_id' => 13],
            ['name' => 'Otuzco ', 'department_id' => 13],
            ['name' => 'Pacasmayo ', 'department_id' => 13],
            ['name' => 'Pataz ', 'department_id' => 13],
            ['name' => 'Sánchez Carrión ', 'department_id' => 13],
            ['name' => 'Santiago de Chuco ', 'department_id' => 13],
            ['name' => 'Gran Chimú ', 'department_id' => 13],
            ['name' => 'Virú ', 'department_id' => 13],
            ['name' => 'Chiclayo ', 'department_id' => 14],
            ['name' => 'Ferreñafe ', 'department_id' => 14],
            ['name' => 'Lambayeque ', 'department_id' => 14],
            ['name' => 'Lima ', 'department_id' => 15],
            ['name' => 'Barranca ', 'department_id' => 15],
            ['name' => 'Cajatambo ', 'department_id' => 15],
            ['name' => 'Canta ', 'department_id' => 15],
            ['name' => 'Cañete ', 'department_id' => 15],
            ['name' => 'Huaral ', 'department_id' => 15],
            ['name' => 'Huarochirí ', 'department_id' => 15],
            ['name' => 'Huaura ', 'department_id' => 15],
            ['name' => 'Oyón ', 'department_id' => 15],
            ['name' => 'Yauyos ', 'department_id' => 15],
            ['name' => 'Maynas ', 'department_id' => 16],
            ['name' => 'Alto Amazonas ', 'department_id' => 16],
            ['name' => 'Loreto ', 'department_id' => 16],
            ['name' => 'Mariscal Ramón Castilla ', 'department_id' => 16],
            ['name' => 'Requena ', 'department_id' => 16],
            ['name' => 'Ucayali ', 'department_id' => 16],
            ['name' => 'Datem del Marañón ', 'department_id' => 16],
            ['name' => 'Putumayo', 'department_id' => 16],
            ['name' => 'Tambopata ', 'department_id' => 17],
            ['name' => 'Manu ', 'department_id' => 17],
            ['name' => 'Tahuamanu ', 'department_id' => 17],
            ['name' => 'Mariscal Nieto ', 'department_id' => 18],
            ['name' => 'General Sánchez Cerro ', 'department_id' => 18],
            ['name' => 'Ilo ', 'department_id' => 18],
            ['name' => 'Pasco ', 'department_id' => 19],
            ['name' => 'Daniel Alcides Carrión ', 'department_id' => 19],
            ['name' => 'Oxapampa ', 'department_id' => 19],
            ['name' => 'Piura ', 'department_id' => 20],
            ['name' => 'Ayabaca ', 'department_id' => 20],
            ['name' => 'Huancabamba ', 'department_id' => 20],
            ['name' => 'Morropón ', 'department_id' => 20],
            ['name' => 'Paita ', 'department_id' => 20],
            ['name' => 'Sullana ', 'department_id' => 20],
            ['name' => 'Talara ', 'department_id' => 20],
            ['name' => 'Sechura ', 'department_id' => 20],
            ['name' => 'Puno ', 'department_id' => 21],
            ['name' => 'Azángaro ', 'department_id' => 21],
            ['name' => 'Carabaya ', 'department_id' => 21],
            ['name' => 'Chucuito ', 'department_id' => 21],
            ['name' => 'El Collao ', 'department_id' => 21],
            ['name' => 'Huancané ', 'department_id' => 21],
            ['name' => 'Lampa ', 'department_id' => 21],
            ['name' => 'Melgar ', 'department_id' => 21],
            ['name' => 'Moho ', 'department_id' => 21],
            ['name' => 'San Antonio de Putina ', 'department_id' => 21],
            ['name' => 'San Román ', 'department_id' => 21],
            ['name' => 'Sandia ', 'department_id' => 21],
            ['name' => 'Yunguyo ', 'department_id' => 21],
            ['name' => 'Moyobamba ', 'department_id' => 22],
            ['name' => 'Bellavista ', 'department_id' => 22],
            ['name' => 'El Dorado ', 'department_id' => 22],
            ['name' => 'Huallaga ', 'department_id' => 22],
            ['name' => 'Lamas ', 'department_id' => 22],
            ['name' => 'Mariscal Cáceres ', 'department_id' => 22],
            ['name' => 'Picota ', 'department_id' => 22],
            ['name' => 'Rioja ', 'department_id' => 22],
            ['name' => 'San Martín ', 'department_id' => 22],
            ['name' => 'Tocache ', 'department_id' => 22],
            ['name' => 'Tacna ', 'department_id' => 23],
            ['name' => 'Candarave ', 'department_id' => 23],
            ['name' => 'Jorge Basadre ', 'department_id' => 23],
            ['name' => 'Tarata ', 'department_id' => 23],
            ['name' => 'Tumbes ', 'department_id' => 24],
            ['name' => 'Contralmirante Villar ', 'department_id' => 24],
            ['name' => 'Zarumilla ', 'department_id' => 24],
            ['name' => 'Coronel Portillo ', 'department_id' => 25],
            ['name' => 'Atalaya ', 'department_id' => 25],
            ['name' => 'Padre Abad ', 'department_id' => 25],
            ['name' => 'Purús', 'department_id' => 25]
        ]);
    }
}
